CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE TABLE profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    username varchar(50) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    role varchar(30) NOT NULL,
    CONSTRAINT chk_profiles_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_profiles_email ON profiles (email);
CREATE INDEX idx_profiles_username ON profiles (username);

CREATE TABLE houses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_rooms integer NOT NULL,
    amount_bathrooms integer NOT NULL
);

CREATE TABLE garages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity integer NOT NULL
);

CREATE TABLE characters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id bigint NOT NULL,
    house_id bigint NOT NULL UNIQUE,
    garage_id bigint NOT NULL UNIQUE,
    name varchar(50) NOT NULL,
    balance numeric(12,2) NOT NULL DEFAULT 0,
    gender varchar(30) NOT NULL,
    skincolor varchar(30) NOT NULL,
    eyecolor varchar(30) NOT NULL,
    height varchar(30) NOT NULL,
    weight varchar(30) NOT NULL,
    CONSTRAINT fk_characters_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_characters_house FOREIGN KEY (house_id) REFERENCES houses(id) ON DELETE CASCADE,
    CONSTRAINT fk_characters_garage FOREIGN KEY (garage_id) REFERENCES garages(id) ON DELETE CASCADE,
    CONSTRAINT chk_characters_gender CHECK (gender IN ('MALE', 'FEMALE', 'NON_BINARY')),
    CONSTRAINT chk_characters_skincolor CHECK (skincolor IN ('LIGHT', 'MEDIUM', 'DARK')),
    CONSTRAINT chk_characters_eyecolor CHECK (eyecolor IN ('BROWN', 'BLUE', 'GREEN', 'GRAY'))
);

CREATE TABLE vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garage_id bigint NOT NULL,
    model varchar(50) NOT NULL,
    type varchar(30) NOT NULL,
    plate_number varchar(20) NOT NULL UNIQUE,
    CONSTRAINT fk_vehicles_garage FOREIGN KEY (garage_id) REFERENCES garages(id) ON DELETE CASCADE,
    CONSTRAINT chk_vehicles_type CHECK (type IN ('CAR', 'MOTORCYCLE', 'TRUCK', 'VAN'))
);

CREATE TABLE drugs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    type varchar(30) NOT NULL,
    CONSTRAINT chk_drugs_type CHECK (type IN ('WEED', 'COCAINE', 'METH', 'PILLS'))
);

CREATE TABLE character_drug (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id bigint NOT NULL,
    drug_id bigint NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT fk_character_drug_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_character_drug_drug FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE,
    CONSTRAINT uk_character_drug_character_drug UNIQUE (character_id, drug_id)
);

CREATE TABLE quests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    description text NOT NULL,
    reward numeric(12,2) NOT NULL
);

CREATE TABLE character_quest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id bigint NOT NULL,
    quest_id bigint NOT NULL,
    status varchar(30) NOT NULL,
    accepted_at timestamp NOT NULL,
    CONSTRAINT fk_character_quest_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_character_quest_quest FOREIGN KEY (quest_id) REFERENCES quests(id) ON DELETE CASCADE,
    CONSTRAINT uk_character_quest_character_quest UNIQUE (character_id, quest_id),
    CONSTRAINT chk_character_quest_status CHECK (status IN ('AVAILABLE', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED'))
);

CREATE TABLE gangs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    type varchar(30) NOT NULL,
    CONSTRAINT chk_gangs_type CHECK (type IN ('STREET', 'MAFIA', 'CARTEL', 'BIKER'))
);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_profile_id bigint,
    actor_username varchar(50),
    actor_role varchar(30),
    action varchar(20) NOT NULL,
    entity_name varchar(100) NOT NULL,
    entity_id bigint,
    request_method varchar(10) NOT NULL,
    request_path varchar(255) NOT NULL,
    old_values text,
    new_values text,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_log_actor_profile FOREIGN KEY (actor_profile_id) REFERENCES profiles(id) ON DELETE SET NULL,
    CONSTRAINT chk_audit_log_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT chk_audit_log_actor_role CHECK (actor_role IS NULL OR actor_role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_audit_log_changed_at ON audit_log (changed_at DESC);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_name, entity_id);
CREATE INDEX idx_audit_log_actor_profile ON audit_log (actor_profile_id);

CREATE TABLE gang_affiliations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id bigint NOT NULL,
    gang_id bigint NOT NULL,
    join_date date NOT NULL,
    CONSTRAINT fk_gang_aff_char FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_gang_aff_gang FOREIGN KEY (gang_id) REFERENCES gangs(id) ON DELETE CASCADE,
    CONSTRAINT uk_gang_affiliations_character_gang UNIQUE (character_id, gang_id)
);
